### ISSUE TITLE
Extra whitespaces in short fast io

### ISSUE THREAD

**Issue by tehnar** [Nikitosh/SPbAU-Generation-Z-Team-Reference#1]
```
inline int readInt() {
  int s = 0, c = getchar(), x = 0;
```

should be changed to

```
inline int readInt() {
  int s = 0, c = readChar(), x = 0;
```

since your code doesn't work with extra whitespaces between numbers (for example, Windows line breaks \r\n)

**Comment by Nikitosh** [comment]
@tehnar 
Thanks, we'll fix it as soon as possible

**Comment by Nikitosh** [comment]
@tehnar 
Fixed

**Comment by Nikitosh** [comment]
@tehnar 
Fixed
